[package]
name = "slime_chess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
colored = "2.0.4"
console = "0.15.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
